### ISSUE TITLE
Holi, estoy en 4t de la etsinf, puedo preguntarte una cosa?

### ISSUE THREAD

**Issue by dkdk22** [6CRIPT/etsinf4#1]
Te quería preguntar cómo es el examen de prácticas de LPPL. Y también pedir-te si puedes subir la parte final de las prácticas  de LPPL porfa, para comparar con la mía. Gracias, que vaya todo muy bien.

**Comment by 6CRIPT** [comment]
Hola buenas, 

La parte 3 y final del proyecto de LPPL ya está subida en el repo, es un archivo comprimido.

Respecto al examen, es hacer una función más para el compilador, aunque más compleja que las que te piden hacer para el proyecto. Si no recuerdo mal fue como una especia de mezcla entre un bucle y algo más. Es en el laboratorio, con los ordenadores en modo examen. Se hace rápido, aunque no es fácil, comparado con otros exámenes de práctica como los de APR. Diría que es una dificultad media-alta aunque se hace rápido.

Suerte con los exámenes y feliz navidad. 🎅🎄

**Comment by dkdk22** [comment]
Muchísimas gracias tio!! ❤️
Feliz Navidad
Y si también tienes exámenes mucha suerte!!💪💪
